backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

locale: "sr"

collections:
  - name: "blog"
    label: "Блог постови"
    label_singular: "Блог пост"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Наслов", name: "title", widget: "string" }
      - { label: "Датум", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - {
          label: "Категорија",
          name: "category",
          widget: "select",
          options:
            [
              "Stručni tekst",
              "Naučni rad",
              "Ispovest pacijenta",
              "Saveti",
              "Aktuelnosti",
            ],
        }
      - { label: "Кратак опис", name: "excerpt", widget: "text" }
      - {
          label: "Слика (опционо)",
          name: "image",
          widget: "image",
          required: false,
        }
      - { label: "Текст", name: "body", widget: "markdown" }
