backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

locale: "sr"

collections:
  - name: "blog"
    label: "Blog postovi"
    label_singular: "Blog post"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Naslov", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - {
          label: "Kategorija",
          name: "category",
          widget: "select",
          options:
            [
              "Stručni tekst",
              "Naučni rad",
              "Ispovest pacijenta",
              "Saveti",
              "Aktuelnosti",
            ],
        }
      - { label: "Kratak opis", name: "excerpt", widget: "text" }
      - {
          label: "Slika (opciono)",
          name: "image",
          widget: "image",
          required: false,
        }
      - { label: "Tekst", name: "body", widget: "markdown" }
